/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mutaki.hexadraw;

import static com.mutaki.hexadraw.ComponentNames.CREATE_CIRCUIT_BTN;
import static com.mutaki.hexadraw.ComponentNames.SAVE_BTN;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import com.mutaki.hexadraw.io.SaveableWrapper;
import com.mutaki.hexadraw.io.Saveables;

public class App {
    public static void main(String[] args) {
	SwingUtilities.invokeLater(() -> new App());
    }

    private final JFrame frame;

    private JPanel drawPanel;
    private Saveables saveables = new Saveables();

    public App() {
	frame = new JFrame("Hexa-Draw");
	frame.setName(ComponentNames.MAIN_FRAME);
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	frame.setSize(800, 600);
	frame.setLocationRelativeTo(null);

	JButton createCircuitBtn = new JButton("Create Circuit");
	createCircuitBtn.setName(CREATE_CIRCUIT_BTN);
	createCircuitBtn.addActionListener(this::createCircuit);

	JButton saveBtn = new JButton("Save");
	saveBtn.setName(SAVE_BTN);
	saveBtn.addActionListener(e -> saveables.save());

	JPanel topPanel = new JPanel();
	topPanel.add(createCircuitBtn);
	topPanel.add(saveBtn);

	frame.add(topPanel, BorderLayout.NORTH);


	frame.setVisible(true);
    }

    private void createCircuit(ActionEvent e) {

	DialogResult dialogResult = CreateCircuitDialog.showDialog(frame);
	saveables.add(new SaveableWrapper(new Circuit(dialogResult.name),
		dialogResult.location));
	if (drawPanel == null) {
	    drawPanel = new JPanel() {
		// just for show
		protected void paintComponent(Graphics g) {
		    super.paintComponent(g);
		    Graphics2D g2d = (Graphics2D) g;
		    g2d.setFont(new Font("Arial", Font.PLAIN, 12));
		    g2d.drawString("Circuit opened!", 50, 50);
		}
	    };
	    frame.add(drawPanel, BorderLayout.CENTER);
	    frame.revalidate();
	}
    }
}
