/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mutaki.hexadraw;

import static com.mutaki.hexadraw.ComponentNames.CREATE_CIRCUIT_BTN;
import static com.mutaki.hexadraw.ComponentNames.SAVE_BTN;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
	SwingUtilities.invokeLater(App::new);
    }

    private JFrame frame;
    private JPanel drawPanel;

    private Circuit circuit;

    public App() {
	frame = new JFrame("Hexa-Draw");
	frame.setName(ComponentNames.MAIN_FRAME);
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	frame.setSize(800, 600);
	frame.setLocationRelativeTo(null);

	JButton createCircuitBtn = new JButton("Create Circuit");
	JButton saveBtn = new JButton("Save");
	saveBtn.addActionListener(this::save);

	JPanel topPanel = new JPanel();
	topPanel.add(createCircuitBtn);
	topPanel.add(saveBtn);

	frame.add(topPanel, BorderLayout.NORTH);

	createCircuitBtn.addActionListener(this::createCircuit);
	// Names help identify components for window licker
	createCircuitBtn.setName(CREATE_CIRCUIT_BTN);
	saveBtn.setName(SAVE_BTN);

	frame.setVisible(true);
    }

    private void createCircuit(ActionEvent e) {

	String circuitName = CreateCircuitDialog.showDialog(frame);
	this.circuit = new Circuit(circuitName);

	if (drawPanel == null) {
	    drawPanel = new JPanel() {
		// just for show
		protected void paintComponent(Graphics g) {
		    super.paintComponent(g);
		    Graphics2D g2d = (Graphics2D) g;
		    g2d.setFont(new Font("Arial", Font.PLAIN, 12));
		    g2d.drawString("Circuit " + circuitName + " opened!", 50, 50);
		}
	    };
	    frame.add(drawPanel, BorderLayout.CENTER);
	    frame.revalidate();
	}
    }

    private void save(ActionEvent actionevent1) {
	JFileChooser fileChooser = new JFileChooser();
	fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	fileChooser.setName(ComponentNames.CIRCUIT_LOCATION_FILE_CHOOSER);

	int result = fileChooser.showSaveDialog(null);
	if (result == JFileChooser.APPROVE_OPTION) {
	    File selectedFile = fileChooser.getSelectedFile();
	    new JsonCircuitFileWriter(circuit).write(selectedFile.toPath());
	}

    }
}
