# For info about what's going on here, read this.
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
hamcrest = "3.0"
assertj-swing = "3.17.1"

[libraries]
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
assertj-swing = { group = "org.assertj", name = "assertj-swing", version.ref = "assertj-swing" }
